### ISSUE TITLE
why is this in public?

### ISSUE THREAD

**Issue by chikashimiyama** [parednuw/Metronome#10]
https://github.com/parednuw/Metronome/blob/f16f735ba33e7f9d4e828f7ab600c23d3fc5b1af/Source/MainComponent.h#L45

should be in private.

Also is it a good place to declare the "state" of the metronome or timer in the GUI class? 
I understand when a enum such as

enum class ButtonColor
{
     Red,
     Blue,
     Gray
}

are in the GUI class but the state of the timer or metronome itself is unrelated to GUI to me.

**Comment by parednuw** [comment]
👍 move states into private and will take care of ownership in https://github.com/parednuw/Metronome/issues/17
