### ISSUE TITLE
Redundant ifs

### ISSUE THREAD

**Issue by chikashimiyama** [parednuw/Metronome#16]
https://github.com/parednuw/Metronome/blob/f16f735ba33e7f9d4e828f7ab600c23d3fc5b1af/Source/MainComponent.cpp#L164-L175

> mPracticeTimer.setPracticeTimer(5 * i);

would suffice

**Comment by parednuw** [comment]
Ouh man, yeah I get it. The if-statements are already embedded in the users choice
