### ISSUE TITLE
Why states are managed by another class?

### ISSUE THREAD

**Issue by chikashimiyama** [parednuw/Metronome#17]
https://github.com/parednuw/Metronome/blob/f16f735ba33e7f9d4e828f7ab600c23d3fc5b1af/Source/MainComponent.h#L61C1-L62

It looks like PracticeTimer and Metronome's states are possessed by another class. why?
Component (GUI) should reflect the states of both but should not own the states of them conceptually.

**Comment by parednuw** [comment]
ownership of state of practice timer is solved in https://github.com/parednuw/Metronome/pull/36
