### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by chikashimiyama** [parednuw/Metronome#3]
https://github.com/parednuw/Metronome/blob/f16f735ba33e7f9d4e828f7ab600c23d3fc5b1af/Source/Main.cpp#L12

Remove all comments in the code base.

I know this is radical. Many programmers say comments are helpful and necessary, yet other many programmers say comments are harmful. we are in the second camp

The justification for the second camp is
1. comments are just excuses for the losers who cannot write clean code and let the code talk to the reader.
2. If you update the code and forget to update comments it just creates confusion

It's up to you to decide if you enter our camp and I think it really depends on each company's coding culture.

N.B. necessary signature / copyright are of course exceptions.

**Comment by parednuw** [comment]
Thanks! I am pro no comments and let the code tell the reader what's happening.

I'll go ahead and delete all comments, also those meant as "seperator".
