### ISSUE TITLE
redundant declaration

### ISSUE THREAD

**Issue by chikashimiyama** [parednuw/Metronome#8]
If you do nothing in constructor you don't have to declare and define.

https://github.com/parednuw/Metronome/blob/f16f735ba33e7f9d4e828f7ab600c23d3fc5b1af/Source/PracticeTimer.cpp#L13

**Comment by parednuw** [comment]
Because I added the initialization of variables to the constructors, there is no more redundant declaration in the code.
https://github.com/parednuw/Metronome/issues/11
